### ISSUE TITLE
Document Drafts: Proposal, Website & Mock-up.

### ISSUE THREAD

**Issue by EdwardRutz** [edwardrz/music-timeline-bullet-journal#2]
- [X] Submit site-draft of website views (9/12/17)
- [X] Submit page mockups.

[capstone-timeline-proposal-draft.pdf](https://github.com/edwardrz/music-timeline-bullet-journal/files/1297960/capstone-timeline-proposal-draft.pdf)
[capstone-timeline-site-draft.pdf](https://github.com/edwardrz/music-timeline-bullet-journal/files/1297962/capstone-timeline-site-draft.pdf)
[Draft Mockup.pdf](https://github.com/edwardrz/music-timeline-bullet-journal/files/1297961/Draft.Mockup.pdf)
[TimelineMockup.pdf](https://github.com/edwardrz/music-timeline-bullet-journal/files/1300839/TimelineMockup.pdf)

**Comment by edwardrz** [comment]
[capstone-timeline-site-draft.pdf](https://github.com/edwardrz/music-timeline-bullet-journal/files/1296231/capstone-timeline-site-draft.pdf)
